### ISSUE TITLE
> at begin of line freezes SublimeText

### ISSUE THREAD

**Issue by arnauldvm** [mrchief/AsciiDoc.SublimeText2#8] opened 2014-09-25 12:04 UTC
Typing the character '>' at the beginning of a line freezes SublimeText.

Typing a space foolowed by the character '>' at the beginning of a line, then deleting the space freezes SublimeText.

- SublimeText 2.0.2, Build 2221, Windows 7
- AsciiDoc package for Sublime Text2 v2013.07.01.20.56.30

**Comment by mrchief** [comment] 2015-02-09 20:29
Duplicate of #5?

**Closed** 2015-02-09 20:30 UTC
